# Generated by Django 5.0 on 2024-01-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_message_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='sender',
        ),
    ]
