# Generated by Django 5.0 on 2024-01-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_user_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(blank=True, default='text', null=True),
        ),
    ]
