# Generated by Django 5.0 on 2024-01-11 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='message/media')),
                ('file', models.FileField(blank=True, null=True, upload_to='message/media')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_attachments', to='chat.message')),
            ],
        ),
    ]
