# Generated by Django 5.0 on 2024-01-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_messageattachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachments',
            name='media_type',
            field=models.CharField(blank=True, choices=[('file', 'file'), ('image', 'image')], max_length=10, null=True),
        ),
    ]
