# Generated by Django 5.0 on 2024-01-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_messageattachments_media_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageattachments',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.ManyToManyField(to='chat.messageattachments'),
        ),
    ]
