# Generated by Django 5.0 on 2024-01-11 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_message_content_alter_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachments',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message'),
        ),
    ]
