# Generated by Django 5.0 on 2024-01-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_messageattachments_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageattachments',
            old_name='file',
            new_name='media_file',
        ),
    ]
