# Generated by Django 5.0 on 2024-01-12 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_rename_file_messageattachments_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachments',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message'),
        ),
    ]
