# Generated by Django 5.0 on 2023-12-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0006_alter_board_authorize_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='banner',
            field=models.ImageField(upload_to='taskboard/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
