# Generated by Django 5.0 on 2023-12-31 17:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0007_alter_board_description_alter_board_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='authorize_users',
        ),
        migrations.AddField(
            model_name='board',
            name='authorize_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=None),
        ),
    ]
