# Generated by Django 5.0 on 2023-12-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0008_remove_board_authorize_users_board_authorize_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='creator',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='creator',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='taskitem',
            old_name='creator',
            new_name='user',
        ),
    ]
