# Generated by Django 5.0 on 2024-01-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0010_alter_board_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
