# Generated by Django 5.0 on 2024-01-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0013_alter_board_title_alter_task_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='taskboard/'),
        ),
    ]
