# Generated by Django 5.0 on 2024-01-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0015_alter_task_created_at_alter_task_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
