# Generated by Django 5.0 on 2024-01-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0016_task_position_taskitem_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
