# Generated by Django 5.0 on 2024-01-07 04:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0018_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='uuid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True),
        ),
    ]
