# Generated by Django 5.0 on 2024-01-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0019_board_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='uuid',
        ),
        migrations.AddField(
            model_name='board',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
