# Generated by Django 5.0 on 2024-01-11 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0021_boardinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinvitation',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='task_board.board'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_items', to='task_board.board'),
        ),
    ]
