# Generated by Django 5.0 on 2024-01-11 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0022_alter_boardinvitation_board_alter_taskitem_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_board.taskitem'),
        ),
    ]
