# Generated by Django 5.0 on 2024-01-16 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0025_taskcomment_taskattachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='task_board.task'),
        ),
    ]
