# Generated by Django 5.0 on 2024-01-16 11:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0028_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='authorize_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=None),
        ),
    ]
