# Generated by Django 5.0 on 2024-01-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0029_task_authorize_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinvitation',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
