# Generated by Django 5.0 on 2024-02-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0030_alter_boardinvitation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
