# Generated by Django 5.0 on 2024-02-16 11:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_board', '0031_board_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='authorize_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='task',
            name='authorize_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
